version: "3.5"

services:
  api01: &api
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8081:8000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8082:8000"

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "20MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql.conf
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "330MB"

networks:
  default:
    driver: bridge
    name: rinha-2024-q1
