# for use with conda (https://docs.conda.io/en/latest/miniconda.html):
# conda env create -f environment.yml
name: "rinha-2024-Q1"
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
